.data
	;------------png coord----------
	bomb_add location <144, 134, 29, 46>
	bomb_icon location <184,117, 30, 29>
	bullet_zero location <112, 2, 9, 17>
	bullet_one location <66, 238, 8, 15>
	bullet_add location <112, 117, 30, 46>
	ememy_b location <2, 2, 108, 164>
	ememy_m location <130, 2, 69, 89>
	ememy_s location <201, 88, 39, 27>
	explosion_one location <216, 117, 26, 26>
	explosion_two location <144, 93, 38, 39>
	explosion_three location <201, 44, 40, 42>
	hero_one location <66, 168, 62, 68>
	hero_two location <2, 168, 62, 75>
	pause_button location <175, 148, 22, 23>
	resume_buttion location <216, 145, 25, 27>
	smoke_one location <201, 2, 48, 20>
	smoke_two location <201, 24, 48, 18>
	big_plane location <0, 0, 35, 45>
	small_plane location <0, 0, 25, 19>
	boss_plane location <0, 0, 82, 121>
	hero_plane location <0, 0, 50, 54>
	pause_png location <0, 0, 20, 21>
	bullet_png location <0, 0, 5, 12>
	btn_png location <0, 0, 80, 23>
	air_png location <0, 0, 214, 42>
	start_loc location <0, 0, 80, 23>
	camera_loc location <0, 0 , 80, 23>
	restart_loc location <120, 300, 80, 23>
	continue_loc location <120, 340, 80, 23>
	exit_loc location <120, 380, 80, 23>
	bk_loc location <0, 1300, 480, 800>
	small_explosion location <0, 0, 23, 19>
	big_explosion location <0, 0, 35, 43>
	boss_explosion location <0, 0, 84, 121>
